name: Auto Pull Request to Develop

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  auto-pr:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request to Develop
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }} # of je feature branch
          base: develop    
          title: "Feature ready for review"
          body: "Automatisch aangemaakt PR naar develop. CI-tests geslaagd."
          reviewers: "teamlid1,teamlid2"